# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

mod_version=v0.1.0+26.1.2-SNAPSHOT
maven_group=org.litkoit

loom_version=1.17-SNAPSHOT
spotless_version=8.9.0
