name: Spotless
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
jobs:
  spotless:
    name: Check code formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Run Spotless check
        run: ./gradlew spotlessCheck
